package io.github.huyz0.jzap.core;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * The engine's own version, read from a resource generated by the build.
 *
 * <p>Part of the cache key, which is why it is not a constant in source: a constant drifts from
 * the build version, and a drifted version would let a cache written by one engine be reused by
 * another that computes different verdicts.
 */
final class EngineVersion {

    private static final String VALUE = load();

    private EngineVersion() {
    }

    public static String get() {
        return VALUE;
    }

    private static String load() {
        try (InputStream in = EngineVersion.class.getResourceAsStream("version.properties")) {
            if (in == null) {
                return "unknown";
            }
            Properties properties = new Properties();
            properties.load(in);
            return properties.getProperty("version", "unknown");
        } catch (IOException e) {
            return "unknown";
        }
    }
}
