package io.github.huyz0.jzap.minion;

import io.github.huyz0.jzap.agent.ClassOverrides;
import io.github.huyz0.jzap.agent.CoverageRecorder;
import io.github.huyz0.jzap.agent.LoopGuard;
import io.github.huyz0.jzap.agent.JzapAgent;
import io.github.huyz0.jzap.wire.Channel;
import io.github.huyz0.jzap.wire.Wire;

import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * The forked JVM that actually runs the user's tests.
 *
 * <p>It holds no bytecode library and no serialisation library: mutant and probe bytecode
 * arrive over the wire already generated by the controller. What it does own is everything
 * that must happen in the same process as the code under test — class redefinition, probe
 * collection, and test execution.
 *
 * <p>Process isolation is what makes hang handling possible at all. A mutant that loops
 * forever cannot be stopped by interrupting a thread, so the controller kills this process
 * and starts another. The same isolation stops one mutant's leftover static state from
 * deciding another mutant's verdict.
 */
public final class Minion {

    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("usage: Minion <controller-port>");
            System.exit(2);
        }
        int port = Integer.parseInt(args[0]);
        try (Socket socket = new Socket(InetAddress.getLoopbackAddress(), port);
             Channel channel = new Channel(socket)) {
            new Minion().serve(channel);
        } catch (IOException e) {
            System.err.println("jzap minion: channel failure: " + e);
            System.exit(3);
        }
        System.exit(0);
    }

    private TestHarness harness;

    private void serve(Channel channel) throws IOException {
        while (true) {
            int command;
            try {
                command = channel.readByte();
            } catch (java.io.EOFException e) {
                return;     // controller went away; nothing to report
            }
            switch (command) {
                case Wire.CMD_INIT_COVERAGE -> initCoverage(channel);
                case Wire.CMD_LIST_TESTS -> listTests(channel);
                case Wire.CMD_RUN_TEST_COVERAGE -> runTestForCoverage(channel);
                case Wire.CMD_SET_OVERRIDE -> setOverride(channel);
                case Wire.CMD_CLEAR_OVERRIDES -> clearOverrides(channel);
                case Wire.CMD_RUN_TESTS -> runTests(channel);
                case Wire.CMD_EXIT -> {
                    return;
                }
                default -> {
                    channel.writeByte(Wire.RESP_ERROR);
                    channel.writeString("unknown command " + command);
                    channel.flush();
                }
            }
        }
    }

    private void initCoverage(Channel channel) throws IOException {
        int probeCount = channel.readInt();
        int classes = channel.readInt();
        CoverageRecorder.init(probeCount);
        for (int i = 0; i < classes; i++) {
            String className = channel.readString();
            byte[] bytes = channel.readBytes();
            ClassOverrides.install(className, bytes);
        }
        respondOk(channel);
    }

    private void listTests(Channel channel) throws IOException {
        int rootCount = channel.readInt();
        List<Path> roots = new ArrayList<>(rootCount);
        for (int i = 0; i < rootCount; i++) {
            roots.add(Path.of(channel.readString()));
        }
        try {
            harness = new TestHarness(roots);
            List<String> tests = harness.discover();
            channel.writeByte(Wire.RESP_OK);
            channel.writeInt(tests.size());
            for (String t : tests) {
                channel.writeString(t);
            }
            channel.flush();
        } catch (RuntimeException | LinkageError e) {
            error(channel, "test discovery failed: " + describe(e));
        }
    }

    private void runTestForCoverage(Channel channel) throws IOException {
        String testId = channel.readString();
        requireHarness();
        CoverageRecorder.drain();
        // Counting without a limit: this run is establishing what the unmutated code needs.
        LoopGuard.arm(0);
        long start = System.nanoTime();
        TestHarness.Outcome outcome = harness.run(List.of(testId), false);
        long millis = (System.nanoTime() - start) / 1_000_000L;
        long ticks = LoopGuard.ticks();
        LoopGuard.disarm();
        int[] probes = CoverageRecorder.drain();

        channel.writeByte(Wire.RESP_OK);
        channel.writeBool(outcome.passed());
        channel.writeString(outcome.failureMessage() == null ? "" : outcome.failureMessage());
        channel.writeLong(millis);
        channel.writeLong(ticks);
        channel.writeInt(probes.length);
        for (int p : probes) {
            channel.writeInt(p);
        }
        channel.flush();
    }

    private void setOverride(Channel channel) throws IOException {
        String className = channel.readString();
        byte[] bytes = channel.readBytes();
        try {
            ClassOverrides.install(className, bytes);
            respondOk(channel);
        } catch (RuntimeException | LinkageError e) {
            // A class that cannot even be installed is a non-viable mutant, not a run error.
            error(channel, "cannot install mutant in " + className + ": " + describe(e));
        }
    }

    private void clearOverrides(Channel channel) throws IOException {
        ClassOverrides.removeAll();
        respondOk(channel);
    }

    private void runTests(Channel channel) throws IOException {
        int count = channel.readInt();
        long iterationLimit = channel.readLong();
        List<String> tests = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
            tests.add(channel.readString());
        }
        requireHarness();
        TestHarness.Outcome outcome;
        LoopGuard.arm(iterationLimit);
        try {
            outcome = harness.run(tests, true);
        } finally {
            LoopGuard.disarm();
        }

        byte code;
        if (outcome.runaway()) {
            code = Wire.OUTCOME_RUNAWAY;
        } else if (outcome.nonViable()) {
            code = Wire.OUTCOME_NON_VIABLE;
        } else if (outcome.passed()) {
            code = Wire.OUTCOME_ALL_PASSED;
        } else {
            code = Wire.OUTCOME_FAILED;
        }
        channel.writeByte(Wire.RESP_OK);
        channel.writeByte(code);
        channel.writeString(outcome.failingTest() == null ? "" : outcome.failingTest());
        channel.writeString(outcome.failureMessage() == null ? "" : outcome.failureMessage());
        channel.writeInt(outcome.testsRun());
        channel.flush();
    }

    private void requireHarness() {
        if (harness == null) {
            throw new IllegalStateException("LIST_TESTS must be sent before running tests");
        }
        if (!JzapAgent.isLoaded()) {
            throw new IllegalStateException("jzap agent is not loaded in the minion JVM");
        }
    }

    private static void respondOk(Channel channel) {
        channel.writeByte(Wire.RESP_OK);
        channel.flush();
    }

    private static void error(Channel channel, String message) {
        channel.writeByte(Wire.RESP_ERROR);
        channel.writeString(message);
        channel.flush();
    }

    private static String describe(Throwable t) {
        return t.getClass().getName() + (t.getMessage() == null ? "" : ": " + t.getMessage());
    }
}
